version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: Run tests and collect coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
